version : '3'
services:
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_api
    ports:
      - "3306:3306"
    volumes:
      - "v-mysql-docker-restapi:/var/lib/mysql"
volumes: 
  v-mysql-docker-restapi: